### ISSUE TITLE
Flok assumes the location of binaries?

### ISSUE THREAD

**Issue by pl-gauthier** [munshkr/flok#67]
So I tried :

`flok-repl -H ws://localhost:3000 -s YmUwNjhjNTYtNDRlYi00ZGNjLTk2NTgtNTJhZDFmMWI1ZmMz -t sclang`

but got :

`[unknown err] /bin/sh: /usr/local/bin/sclang: No such file or directory`

because on my machine the command `which sclang` returns `/usr/bin/sclang`.

So I tried for the fun :

`flok-repl -H ws://localhost:3000 -s YmUwNjhjNTYtNDRlYi00ZGNjLTk2NTgtNTJhZDFmMWI1ZmMz -t /usr/bin/sclang`

which of course replied promptly with :

`Unknown type /usr/bin/sclang. Must be one of: [ 'tidal', 'sclang', 'remote_sclang', 'foxdot' ]`

**Comment by munshkr** [comment]
Hi! I'm afraid the path is hardcoded to `/usr/local/bin/sclang` right now. Sorry! I'll try to fix this soon.

To run a custom REPL, skip the `-t` option, just pass the name of the command at the end, like this:
```
flok-repl -H ws://localhost:3000 -s YmUwNjhjNTYtNDRlYi00ZGNjLTk2NTgtNTJhZDFmMWI1ZmMz -n sclang -- /usr/bin/sclang
```
In this case I'm also setting the name of the target as `sclang` with the `-n` option.
Unfortunately, this won't work right with sclang because of some weird behaviors of the interpreter.

You can also try to use the `remote_sclang` target if you want. You will have to install [this quark](https://github.com/munshkr/FlokQuark) and then run the repl with `-t remote_sclang -n sclang`.

**Comment by jwaldmann** [comment]
Please document this way of calling an executable. `-- <exec>` is not listed in the output of `flok-repl -h`. Also, `--list-types` does suggest that `-t` must be one of those four types listed, while here it must be skipped. So there is an extra type `none`?

**Comment by munshkr** [comment]
> Please document this way of calling an executable. `-- <exec>` is not listed in the output of `flok-repl -h`. Also, `--list-types` does suggest that `-t` must be one of those four types listed, while here it must be skipped. So there is an extra type `none`?
> 
> I can write such a text but I'm not confident about the details.

Right. I took that suggestion to issue #68

**Comment by munshkr** [comment]
Fixed on https://github.com/munshkr/flok/commit/2e0f62098f6adb701d26af2852b2b45f2ea750b9
Now it runs `sclang` by default. You can specify a custom path as an extra option, like this:
```sh
flok-repl -t sclang --extra '{ "sclang": "/my/path/to/sclang" }'
```
Let me know if it works for you now @pl-gauthier

**Comment by pl-gauthier** [comment]
> Let me know if it works

Yep it do.
Thanks ! :-)
