### ISSUE TITLE
Tidal package installed but doesn't show up in `ghc-pkg list`

### ISSUE THREAD

**Issue by juaneduardoflores** [munshkr/flok#85]
I use vim-tidal (thank you btw!), and it works fine there.
I recently wiped my computer and installed everything from scratch. After the wipe flok-repl didn't work saying that it could not find the tidal package. I thought it was strange that tidal works with vim-tidal but was not listed with `ghc-pkg list`, and `cabal list tidal` shows that the latest version was not installed.
After much google search I found that the command `ghc-pkg -f /Users/youruser/.cabal/store/ghc-8.8.4/package.db list` does list tidal. So I changed the tidal.js file to include that and it works!

I'm wondering if cabal changed in some way in the latest versions. I admittedly don't know much about this, just wanted to share in case it was any use.

**Comment by jwaldmann** [comment]
yes this is a recent change in cabal/ghc that comes with much heated debate https://gitlab.haskell.org/ghc/ghc/-/issues/17341 and requires busy-work in tidal https://github.com/tidalcycles/Tidal/issues/706

**Comment by santoluigi** [comment]
hi

i have the same problem how you change tidal.js?

**Comment by munshkr** [comment]
Hi @juaneduardoflores ! Thanks for reporting this. It is an issue with recent versions of GHC as @jwaldmann points. 
`flok-repl` uses `ghc-pkg` to find the data directory of Tidal, which contains the bootstrap script `BootTidal.hs` that initializes Tidal. 

`vim-tidal` works because it bundles the `BootTidal.hs` itself, but I don't like that approach anymore because I need to keep it up to date constantly whenever Tidal publishes a new version, and even then, it would only work with the latest Tidal version.

I should find a better workaround for this though!

**Comment by santoluigi** [comment]
ok thanks now work good

**Comment by munshkr** [comment]
In the end I decided to include the latest BootTidal.sh as a fallback, in case ghc-pkg fails to get tidal data package, so this should be fixed in the next flok-repl v0.4.1
