### ISSUE TITLE
Output code as OSC Message for repl option?

### ISSUE THREAD

**Issue by tmhglnd** [munshkr/flok#91]
Would it be possible for Flok to send out the code as an OSC message as "repl" option instead of specifying a repl? I tried to look into the code myself but couldn't really find a way to get started with setting this up. Maybe this is related to #29 because I believe this is how Troop sends its code to SonicPi.

**Comment by munshkr** [comment]
Hi @tmhglnd, yes, actually there is [a REPL class](https://github.com/munshkr/flok/blob/master/packages/repl/src/repl/sclang.ts#L34-L94) that uses OSC instead of writing/reading to a pipe. This is an alternative REPL type for SuperCollider, which sends OSC the code to sclang through OSC.

If this is for another language/tool (is this for Mercury?), maybe you could define a `MercuryREPL` class and use `RemoteSclangREPL` as an example.

**Comment by tmhglnd** [comment]
Yes, indeed I was thinking making this work with Mercury :). Thanks for the pointers, created a class with the `RemoteSclangREPL` as example and got it working already quite quickly. Will look into some changes and if you don't mind send a pull request

**Comment by munshkr** [comment]
Awesome! I'll be waiting for the PR then :-)

**Comment by tmhglnd** [comment]
Should I first merge my branch to my forked master branch and run a `yarn release` myself or should I send you the pull request for the branch `mercury-repl` that I created and let you handle the new release? Not sure what the best step to proceed is and if you have any preference.

**Comment by munshkr** [comment]
Just create a PR for merging your branch to this repo's master branch. Then I'll review and merge it, and finally release a new version of `flok-repl`. Thanks!

**Comment by munshkr** [comment]
> Maybe this is related to #29 because I believe this is how Troop sends its code to SonicPi.

Thanks for the tip btw! I forgot that Troop supported SonicPi. I'll probably do the same.

**Comment by munshkr** [comment]
Merged https://github.com/munshkr/flok/pull/94
